version: "3.7"
services:
  learner-dashboard: # Work on this MFE for development
      image: "docker.io/overhangio/openedx-learner-dashboard-dev:17.0.0"
      ports:
          - "1996:1996"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
          - /home/gradmin/frontend-app-learner-dashboard:/openedx/app
          - /openedx/app/node_modules
      restart: unless-stopped
      environment:
          - "PORT=1996"